sudo: required
services:
  - docker

before_install:
  - docker build -t osvaldoga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run osvaldoga/react-test npm test -- --coverage

after_success:
  - docker build -t osvaldoga/multi-client ./client
  - docker build -t osvaldoga/multi-nginx ./nginx
  - docker build -t osvaldoga/multi-server ./server
  - docker build -t osvaldoga/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
  - docker push osvaldoga/multi-client
  - docker push osvaldoga/multi-nginx
  - docker push osvaldoga/multi-server
  - docker push osvaldoga/multi-worker
